# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class BellatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Generis = channel.unary_unary(
        '/core.Bellator/Generis',
        request_serializer=service__pb2.FeatureVector.SerializeToString,
        response_deserializer=service__pb2.Response.FromString,
        )
    self.GenerisPolo = channel.unary_unary(
        '/core.Bellator/GenerisPolo',
        request_serializer=service__pb2.FeatureVector.SerializeToString,
        response_deserializer=service__pb2.Response.FromString,
        )


class BellatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Generis(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GenerisPolo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BellatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Generis': grpc.unary_unary_rpc_method_handler(
          servicer.Generis,
          request_deserializer=service__pb2.FeatureVector.FromString,
          response_serializer=service__pb2.Response.SerializeToString,
      ),
      'GenerisPolo': grpc.unary_unary_rpc_method_handler(
          servicer.GenerisPolo,
          request_deserializer=service__pb2.FeatureVector.FromString,
          response_serializer=service__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'core.Bellator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
