# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='core',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rservice.proto\x12\x04\x63ore\"\x86\x01\n\rFeatureVector\x12\r\n\x05Title\x18\x01 \x01(\t\x12\x10\n\x08\x43omments\x18\x02 \x01(\x03\x12\x10\n\x08OpenDays\x18\x03 \x01(\x03\x12\x0c\n\x04\x41\x64\x64s\x18\x04 \x01(\x03\x12\x0c\n\x04\x44\x65ls\x18\x05 \x01(\x03\x12\r\n\x05\x46iles\x18\x06 \x01(\x03\x12\x17\n\x0f\x43ouplingAverage\x18\x07 \x01(\x02\"\x1b\n\x08Response\x12\x0f\n\x07Generis\x18\x01 \x01(\t2r\n\x08\x42\x65llator\x12\x30\n\x07Generis\x12\x13.core.FeatureVector\x1a\x0e.core.Response\"\x00\x12\x34\n\x0bGenerisPolo\x12\x13.core.FeatureVector\x1a\x0e.core.Response\"\x00\x62\x06proto3')
)




_FEATUREVECTOR = _descriptor.Descriptor(
  name='FeatureVector',
  full_name='core.FeatureVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Title', full_name='core.FeatureVector.Title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Comments', full_name='core.FeatureVector.Comments', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OpenDays', full_name='core.FeatureVector.OpenDays', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Adds', full_name='core.FeatureVector.Adds', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Dels', full_name='core.FeatureVector.Dels', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Files', full_name='core.FeatureVector.Files', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CouplingAverage', full_name='core.FeatureVector.CouplingAverage', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=158,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='core.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Generis', full_name='core.Response.Generis', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=187,
)

DESCRIPTOR.message_types_by_name['FeatureVector'] = _FEATUREVECTOR
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeatureVector = _reflection.GeneratedProtocolMessageType('FeatureVector', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREVECTOR,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:core.FeatureVector)
  })
_sym_db.RegisterMessage(FeatureVector)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:core.Response)
  })
_sym_db.RegisterMessage(Response)



_BELLATOR = _descriptor.ServiceDescriptor(
  name='Bellator',
  full_name='core.Bellator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=189,
  serialized_end=303,
  methods=[
  _descriptor.MethodDescriptor(
    name='Generis',
    full_name='core.Bellator.Generis',
    index=0,
    containing_service=None,
    input_type=_FEATUREVECTOR,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GenerisPolo',
    full_name='core.Bellator.GenerisPolo',
    index=1,
    containing_service=None,
    input_type=_FEATUREVECTOR,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BELLATOR)

DESCRIPTOR.services_by_name['Bellator'] = _BELLATOR

# @@protoc_insertion_point(module_scope)
